INSERT INTO ROLES (ROLE_NAME) VALUES ('ADMIN');
INSERT INTO ROLES (ROLE_NAME) VALUES ('USER');
INSERT INTO ROLES (ROLE_NAME) VALUES ('WORKER');

INSERT INTO CATEGORIES (CATEGORY_NAME, PICTURE) VALUES ('Autószerelő', '1.jpg');
INSERT INTO CATEGORIES (CATEGORY_NAME, PICTURE) VALUES ('Villanyszerelo', '2.png');
INSERT INTO CATEGORIES (CATEGORY_NAME, PICTURE) VALUES ('Gázszerelő', '1.jpg');


INSERT INTO USERS (USER_TYPE, PASSWORD, USERNAME, ROLE_ID, NAME) VALUES ('Admin', 'admin','admin',1, 'Tomi');
INSERT INTO USERS (USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, LOCATION, NAME, PHONE_NUM) VALUES ('User', 'user','user',2, 'asd@asd.hu', 'Pest', 'Jancsi', '06202121');
INSERT INTO USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, CATEGORY_ID, DESCRIPTION) VALUES ('laci.jpg', 'Worker', 'laci1','laci',3, 'asd@asd.hu', 'Jancsi', '06202121',2, 'jo');
INSERT INTO USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, CATEGORY_ID, DESCRIPTION) VALUES ('peti.jpg','Worker', 'peti1','peti',3, 'peti@asd.hu', 'Péter', '06202121',3, 'rosz');

INSERT INTO LOCATIONS (LOCATION_NAME, WORKER_ID) VALUES ('Pest', 3);
INSERT INTO LOCATIONS(LOCATION_NAME, WORKER_ID) VALUES ('Buda', 3);
INSERT INTO LOCATIONS (LOCATION_NAME, WORKER_ID) VALUES ('Balaton', 3);
INSERT INTO LOCATIONS (LOCATION_NAME, WORKER_ID) VALUES ('Csepel', 3);

INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('olajcsere', '1000-2000 Ft', 3);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('kerekcsere', '5000 Ft', 3);


INSERT INTO MESSAGES (CONTENT, IS_SEEN, SEND_TIMESTAMP, RECIPIENT_ID, SENDER_ID) VALUES ('jonapot kivanok user, laci vagyok', 'false', current_timestamp, 2,3);
INSERT INTO MESSAGES (CONTENT, IS_SEEN, SEND_TIMESTAMP, RECIPIENT_ID, SENDER_ID) VALUES ('jonapot kivanok laci, user vagyok', 'false', current_timestamp, 3,2);

INSERT INTO USERS_FAVORITES (USER_ID, WORKER_ID) VALUES (2,3);
INSERT INTO USERS_FAVORITES (USER_ID, WORKER_ID) VALUES (2,4);

INSERT INTO RATINGS (CONTENT, RATING, TIMESTAMP, SENDER_ID, RECIPIENT_ID) VALUES ('user vsok, lacinak', '2', current_timestamp, 3,2);
INSERT INTO RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) VALUES ('user vok, petinnak', '5', current_timestamp, 4,2);