INSERT INTO ROLES (ROLE) VALUES ('ADMIN');
INSERT INTO ROLES (ROLE) VALUES ('USER');
INSERT INTO ROLES (ROLE) VALUES ('WORKER');


INSERT INTO USERS (PASSWORD, USERNAME, ROLE_ID) VALUES ('admin','admin',1);
INSERT INTO USERS (PASSWORD,USERNAME, ROLE_ID) VALUES ('user','user',2);
INSERT INTO USERS (PASSWORD,USERNAME, ROLE_ID) VALUES ('laci1','laci',3);
