
insert into ROLES (ROLE_NAME) values ('ADMIN');
insert into ROLES (ROLE_NAME) values ('USER');
insert into ROLES (ROLE_NAME) values ('WORKER');
--1-8
insert into CATEGORIES (CATEGORY_NAME, PICTURE) values ('Autószerelõ', '1.png');
insert into CATEGORIES (CATEGORY_NAME, PICTURE) values ('Villanyszerelõ', '2.png');
insert into CATEGORIES (CATEGORY_NAME, PICTURE) values ('Víz-gáz-fûtésszerelõ', '3.png');
insert into CATEGORIES (CATEGORY_NAME, PICTURE) values ('Kertész', '4.png');
insert into CATEGORIES (CATEGORY_NAME, PICTURE) values ('Asztalos', '5.png');
insert into CATEGORIES (CATEGORY_NAME, PICTURE) values ('Festõ', '6.png');
insert into CATEGORIES (CATEGORY_NAME, PICTURE) values ('Háztartási gépszerelõ', '7.png');
insert into CATEGORIES (CATEGORY_NAME, PICTURE) values ('Kõmûves', '8.png');


--1-30
insert into LOCATIONS (LOCATION_NAME) values ('Budapest');
insert into LOCATIONS (LOCATION_NAME) values ('Budapest I.');
insert into LOCATIONS (LOCATION_NAME) values ('Budapest II.');
insert into LOCATIONS (LOCATION_NAME) values ('Budapest III.');
insert into LOCATIONS (LOCATION_NAME) values ('Budapest IV.');
insert into LOCATIONS (LOCATION_NAME) values ('Budapest V.');
insert into LOCATIONS (LOCATION_NAME) values ('Budapest VI.');
insert into LOCATIONS (LOCATION_NAME) values ('Budapest VII.');
insert into LOCATIONS (LOCATION_NAME) values ('Budapest VIII.');
insert into LOCATIONS (LOCATION_NAME) values ('Budapest IX.');
insert into LOCATIONS (LOCATION_NAME) values ('Budapest X.');
insert into LOCATIONS (LOCATION_NAME) values ('Budapest XI.');
insert into LOCATIONS (LOCATION_NAME) values ('Budapest XII.');
insert into LOCATIONS (LOCATION_NAME) values ('Budapest XIII.');
insert into LOCATIONS (LOCATION_NAME) values ('Budapest XIV.');
insert into LOCATIONS (LOCATION_NAME) values ('Budapest XV.');
insert into LOCATIONS (LOCATION_NAME) values ('Budapest XVI.');
insert into LOCATIONS (LOCATION_NAME) values ('Budapest XVII.');
insert into LOCATIONS (LOCATION_NAME) values ('Budapest XVIII.');
insert into LOCATIONS (LOCATION_NAME) values ('Budapest XIX.');
insert into LOCATIONS (LOCATION_NAME) values ('Budapest XX.');
insert into LOCATIONS (LOCATION_NAME) values ('Budapest XXI.');
insert into LOCATIONS (LOCATION_NAME) values ('Budapest XXII.');
insert into LOCATIONS (LOCATION_NAME) values ('Budapest XXIII.');
insert into LOCATIONS (LOCATION_NAME) values ('Gödöllõ');
insert into LOCATIONS (LOCATION_NAME) values ('Gyõr');
insert into LOCATIONS (LOCATION_NAME) values ('Székesfehérvár');
insert into LOCATIONS (LOCATION_NAME) values ('Miskolc');
insert into LOCATIONS (LOCATION_NAME) values ('Debrecen');
insert into LOCATIONS (LOCATION_NAME) values ('Szekszárd');


--1-12
insert into USERS (USER_TYPE, PASSWORD, USERNAME, ROLE_ID, NAME) values ('Admin', '21232F297A57A5A743894A0E4A801FC3','admin',1, 'Tomi');
insert into USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, LOCATION_ID, LAST_LOGIN) values ('user.jpg', 'User', 'EFC847FA5A386A38FCC9D0573BB87272','user',2, 'user@user.hu',  'Lee Sándor', '06309987876', 11, '2017-02-21 13:21:32');
insert into USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, LOCATION_ID) values ('tomi.jpg', 'User', 'EFC847FA5A386A38FCC9D0573BB87272','tomi',2, 'tomi34@gmail.hu',  'Ablakos Tomi', '06309987876',21);
insert into USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, LOCATION_ID) values ('tibor.jpg', 'User', 'EFC847FA5A386A38FCC9D0573BB87272','tibor',2, 'tibi96@asd.hu',  'Terep Tibor', '06309987876',4);
insert into USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, LOCATION_ID) values ('patrik.jpg', 'User', 'EFC847FA5A386A38FCC9D0573BB87272','patrik',2, 'pati@invitel.hu',  'Vízi Patrik', '06309987876',6);
insert into USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, LOCATION_ID) values ('jozsef.jpg', 'User', 'EFC847FA5A386A38FCC9D0573BB87272','jozsef',2, 'jozsi21@gmail.hu', 'Kovács József', '06309987876',7);
insert into USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, LOCATION_ID) values ('gyorgyi.jpg', 'User', 'EFC847FA5A386A38FCC9D0573BB87272','gyorgyi',2, 'gyorgyike@digi.hu', 'Nyugati Györgyi', '06309987876',8);
insert into USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, LOCATION_ID) values ('gergely.jpg', 'User', 'EFC847FA5A386A38FCC9D0573BB87272','gergely',2, 'gergo25@digi.hu', 'Leveles Gergely', '06309987876',24);
insert into USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, LOCATION_ID) values ('erzsi.jpg', 'User', 'EFC847FA5A386A38FCC9D0573BB87272','erzsi',2, 'erzsimama@thome.hu', 'Kovácsné Erzsébet', '06309987876',7);
insert into USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, LOCATION_ID) values ('balazs.jpg', 'User', 'EFC847FA5A386A38FCC9D0573BB87272','balazs',2, 'balazs@freemail.hu', 'Mérnök Balázs', '06309987876',21);
insert into USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, LOCATION_ID) values ('anna.jpg', 'User', 'EFC847FA5A386A38FCC9D0573BB87272','anna',2, 'anna.kiss@gmail.hu', 'Kiss Anna', '06309987876',10);
insert into USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, LOCATION_ID) values ('adam.jpg', 'User', 'EFC847FA5A386A38FCC9D0573BB87272','adam',2, 'adamszalai@citromail.hu', 'Szalai Ádám', '06309987876',26);

--13-20
insert into USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, CATEGORY_ID, DESCRIPTION, LAST_LOGIN, APPROVED) values ('kriszti1992.jpg', 'Worker', 'EFC847FA5A386A38FCC9D0573BB87272','kriszti1992',3, 'kriszti92@gmail.com', 'Kriszti', '062022126',1, 'Foglalkozom régi illetve újabb évjáratú autók szervizelésével, szeretettel várom a mûhelyemben, illetve kiszállásra is van lehetõség!', '2017-02-21 13:21:32','true');
insert into USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, CATEGORY_ID, DESCRIPTION, APPROVED) values ('ferenc.jpg', 'Worker', 'EFC847FA5A386A38FCC9D0573BB87272','ferenc',3, 'ferenc1995@gmail.com', 'Ferenc Ajtós', '06302218787',1, 'Üdv! Fiatalos, de tapasztalt csapat várja Önt szervizünkben Budapesten, a fõ profilunk a japán illetve a koreai gyártmányú autók javítása.','true');
insert into USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, CATEGORY_ID, DESCRIPTION, APPROVED) values ('javito.jpg', 'Worker', 'EFC847FA5A386A38FCC9D0573BB87272','javito',3, 'javitok@gmail.com', 'Javító Jani', '06202233236',1, 'Közel 20 éve foglalkozom BMW, Mercedes, Audi, Opel és egyéb német gyártmányú autók szervizelésével, forduljon bizalommal hozzánk!','true');
insert into USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, CATEGORY_ID, DESCRIPTION, APPROVED) values ('kerekes.jpg', 'Worker', 'EFC847FA5A386A38FCC9D0573BB87272','kerekes',3, 'kerek@gmail.com', 'Kerekes Géza', '06202233236',1, 'Gumis illetve kerékjavító szervizembe várom a vendégeket, bármilyen típusú autóval/tehergépjármûvel foglalkozunk!','true');
insert into USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, CATEGORY_ID, DESCRIPTION, APPROVED) values ('tamas.jpg', 'Worker', 'EFC847FA5A386A38FCC9D0573BB87272','tamas',3, 'tamas13@gmail.com', 'Járvás Tamás', '06709498873',1, 'Nagy kapacitással rendelkezõ szervizemben várom Budapest szívében!','true');
insert into USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, CATEGORY_ID, DESCRIPTION, APPROVED) values ('autos.jpg', 'Worker', 'EFC847FA5A386A38FCC9D0573BB87272','autos',3, 'autospeti@gmail.com', 'Autós Péter', '062022556236',1, 'Motorok, illetve kisteherautók szervizelése is megoldhato nálunk, küldjön üzenetet!','true');
insert into USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, CATEGORY_ID, DESCRIPTION, APPROVED) values ('erika778.jpg', 'Worker', 'EFC847FA5A386A38FCC9D0573BB87272','erika778',3, 'erika778@asd.hu', 'Nagy Erika', '06202126',1, 'Foglaljon idõpontot és autóját akár pár órán belül megvizsgáljuk, a felmérés után az árlistát figyelembe véve kap tõlünk ajánlatot!','true');
insert into USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, CATEGORY_ID, DESCRIPTION, APPROVED) values ('barat.jpg', 'Worker', 'EFC847FA5A386A38FCC9D0573BB87272','barat',3, 'barattamas@gmail.com', 'Barát Tamás', '062022556236',1, 'Alvázjavításra nem talál jobb embert nálam, vegye fel a kapcsolatot!','true');
--21-25
insert into USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, CATEGORY_ID, DESCRIPTION, APPROVED) values ('alma112.jpg','Worker', 'EFC847FA5A386A38FCC9D0573BB87272','alma112',3, 'almaalma@citromail.hu', 'Kovács Alma', '06708765657',2, 'Üdvözlöm! Kedvezményes kiszállási díjjal állok rendelkezésére, az árlistámon mindent megtalál, további információkért küldjön üzenetet!','true');
insert into USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, CATEGORY_ID, DESCRIPTION, APPROVED) values ('peter.jpg','Worker', 'EFC847FA5A386A38FCC9D0573BB87272','peter',3, 'peternagy@citromail.hu', 'Nagy Péter', '06708765657',2, '20 éve villanyszereléssel foglalkozom, a felmérés után képességeimhez mérten bármit meg tudok valósitani!','true');
insert into USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, CATEGORY_ID, DESCRIPTION, APPROVED) values ('laci.jpg','Worker', 'EFC847FA5A386A38FCC9D0573BB87272','laci',3, 'laci1993@citromail.hu', 'László', '06708765657',2, 'Bármilyen villanyszerelési, illetve épületgépészeti munkával keressen bizalommal, velem a leggyorsabban megvalósíthatja terveit! ','true');
insert into USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, CATEGORY_ID, DESCRIPTION, APPROVED) values ('andris5.jpg','Worker', 'EFC847FA5A386A38FCC9D0573BB87272','andris5',3, 'andris1956@citromail.hu', 'Alma András', '067065657',2, 'Új kapcsolók, dugaljak, lámpák felszerelése? Az ilyen gyors munkákat kedvezményes áron végzem el, tudva milyen gyorsan szükség lehet az ilyen apróságokra! ','true');
insert into USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, CATEGORY_ID, DESCRIPTION, APPROVED) values ('feri22.jpg','Worker', 'EFC847FA5A386A38FCC9D0573BB87272','feri22',3, 'ferenc@freemail.hu', 'Szegedi Ferenc', '06708766757',2, 'Nagyobb intézmények, ingatlanok teljeskörû villanyszerelésével is foglalkozom, ilyen munka esetén üzenetben keressen fel mindenképp! ','true');
--26-29
insert into USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, CATEGORY_ID, DESCRIPTION, APPROVED) values ('aladar.jpg','Worker', 'EFC847FA5A386A38FCC9D0573BB87272','aladar',3, 'aladar47@freemail.hu', 'Arany Aladár', '06708766757',3, 'Víz-gáz és fûtéssel is foglalkozom, az árlistán ilyen jellegû feladatokat is megtalál. Leggyakrabban családi házak, illetve új építésû ingatlanok szereléséhez/építkezéséhez hívnak, hívjon Ön is!','true');
insert into USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, CATEGORY_ID, DESCRIPTION, APPROVED) values ('istvan.jpg','Worker', 'EFC847FA5A386A38FCC9D0573BB87272','istvan',3, 'kovacs.istvan@freemail.hu', 'Kovács István', '06708766757',3, '30 éves tapasztalattal rendelkezem, egészen az egyszerû dugulástól a teljes vizesblokk beszereléséig. Ne feledje, ha vízszerelés, akkor Kovács István!','true');
insert into USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, CATEGORY_ID, DESCRIPTION, APPROVED) values ('bence.jpg','Worker', 'EFC847FA5A386A38FCC9D0573BB87272','bence',3, 'bence.kiss@freemail.hu', 'Kiss Bence', '06708766757',3, 'Fiatalos, gyors munkavégzés, kis felár esetén villámfelméréssel, írjon rám :) !','true');
insert into USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, CATEGORY_ID, DESCRIPTION, APPROVED) values ('denes.jpg','Worker', 'EFC847FA5A386A38FCC9D0573BB87272','denes',3, 'denes77@citromail.hu', 'Horváth Dénes', '06207896765',3, 'Fûtésrendszer a fõ szakterületem, ezek közül gázos, elektromos, de akár fatüzeléses megoldásokat is könnyedén szerelek/építek!','true');

--30-33
insert into USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, CATEGORY_ID, DESCRIPTION, APPROVED) values ('lilla12.jpg','Worker', 'EFC847FA5A386A38FCC9D0573BB87272','lilla12',3, 'lilla12@hotmail.hu', 'Fekete Lilla', '0620212229',4, 'Ha szimpatikus, de ugyanakkor tapasztalt munkavállalót keres, keressen fel. Nem csak virágoskertbe!','true');
insert into USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, CATEGORY_ID, DESCRIPTION, APPROVED) values ('kerteszferi.jpg','Worker', 'EFC847FA5A386A38FCC9D0573BB87272','kerteszferi',3, 'kerteszferenc@hotmail.hu', 'Kertész Ferenc', '06304567676',4, 'Faiskolában dolgoztam 10 évig, gyümölcsöskertek gondozásával, erdészeti munkákkal foglalkoznék, kisebb munkaként akár favágással is!','true');
insert into USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, CATEGORY_ID, DESCRIPTION, APPROVED) values ('sandor.jpg','Worker', 'EFC847FA5A386A38FCC9D0573BB87272','sandor',3, 'sandor@hotmail.hu', 'Földes Sándor', '0620212229',4, 'Virágoskertek illetve akár zöldségeskertek karbantartásával kapcsolatban keressen nyugodtan!','true');
insert into USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, CATEGORY_ID, DESCRIPTION, APPROVED) values ('antal.jpg','Worker', 'EFC847FA5A386A38FCC9D0573BB87272','antal',3, 'antalj40@hotmail.hu', 'Jónás Antal', '06704453434',4, '30 éves tapasztalattal rendelkezõ kertész keres családi házat vagy birtokot, amit felügyelhet.','true');
--34-39
insert into USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, CATEGORY_ID, DESCRIPTION, APPROVED) values ('girl126.jpg','Worker', 'EFC847FA5A386A38FCC9D0573BB87272','girl126',3, 'erzsike@asd.hu', 'Erzsébet', '0620222128',5, 'Egyedi bútorok és háztartási eszközök készítésével tervezésével foglalkozunk, ha van bármilyen ötlete vegye fel a kapcsolatot és megnézzük mit tehetünk!','true');
insert into USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, CATEGORY_ID, DESCRIPTION, APPROVED) values ('gabor.jpg','Worker', 'EFC847FA5A386A38FCC9D0573BB87272','gabor',3, 'gabor@gmail.hu', 'Takács Gábor', '067210101',5, 'Kisebb bútorok készítésével foglalkozom, csak a legjobb minõségû alapanyagokból!','true');
insert into USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, CATEGORY_ID, DESCRIPTION, APPROVED) values ('karoly.jpg','Worker', 'EFC847FA5A386A38FCC9D0573BB87272','karoly',3, 'karoly@freemail.hu', 'Tölgyes Károly', '0688799867',5, 'Üdvözlöm! Bármilyen faipari termék elõlállítását ránk bízhatja a gerendától egészen a hajópadlóig!','true');
insert into USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, CATEGORY_ID, DESCRIPTION, APPROVED) values ('lajos.jpg','Worker', 'EFC847FA5A386A38FCC9D0573BB87272','lajos',3, 'lajos@gmail.hu', 'Fehér Lajos', '0620222128',5, 'Fa asztalok, székek egyedi megrendelésre, limitált példányszámban, küldjön üzenetet árajánlatra!','true');
insert into USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, CATEGORY_ID, DESCRIPTION, APPROVED) values ('marcell.jpg','Worker', 'EFC847FA5A386A38FCC9D0573BB87272','marcell',3, 'marcell@gmail.hu', 'Marcell', '0620232221',5, '30 éves tapasztalattal rendelkezõ asztalosmester várja a hívását.','true');
insert into USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, CATEGORY_ID, DESCRIPTION, APPROVED) values ('lali.jpg','Worker', 'EFC847FA5A386A38FCC9D0573BB87272','lali',3, 'laliapu@gmail.hu', 'Gerendás Lajos', '0620232221',5, 'Mûhelyemben bármilyen szekrény, gardróbszekrény, konyhabútor, nappali bútor vagy komód készítését vállalom!','true');

--40-42
insert into USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, CATEGORY_ID, DESCRIPTION, APPROVED) values ('szilvi.jpg','Worker', 'EFC847FA5A386A38FCC9D0573BB87272','szilvi',3, 'szilvi79@freemail.hu', 'Barát Szilvia', '06202120',6, 'Szobafestés most kedvezményes áron, a hely méretétõl függõen, akár mennyiségi kedvezménnyel is, keressen bátran!','true');
insert into USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, CATEGORY_ID, DESCRIPTION) values ('festo.jpg','Worker', 'EFC847FA5A386A38FCC9D0573BB87272','festo',3, 'oli55@freemail.hu', 'Kocka Olivér', '06202189920',6, 'Az anyag miatt se aggódjon, a festék keverését én magam végzem minõségi alapanyagokból, évtizedes szakértelemmel!');
insert into USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, CATEGORY_ID, DESCRIPTION, APPROVED) values ('joe.jpg','Worker', 'EFC847FA5A386A38FCC9D0573BB87272','joe',3, 'joe21@freemail.hu', 'Barna Jónás', '06202189920',6, 'Mûvészi képek festésével is foglalkoztam pár évig, így akár gyermekszobai rajzokat is festhetek egyedi ötlet alapján.','true');
--43-46
insert into USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, CATEGORY_ID, DESCRIPTION, APPROVED) values ('david.jpg','Worker', 'EFC847FA5A386A38FCC9D0573BB87272','david',3, 'david33@freemail.hu', 'Budai Dávid', '06202189920',7, 'Kedvezõ kiszállási díjjal vállalom mosógépek, hûtõgépek, mosogatógépek szervizelését, keressen üzenetben ajánlatért!','true');
insert into USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, CATEGORY_ID, DESCRIPTION, APPROVED) values ('jani.jpg','Worker', 'EFC847FA5A386A38FCC9D0573BB87272','jani',3, 'jancsika@freemail.hu', 'Pesti János', '06202189920',7, 'Pesti János, a mosógépek szakértõje: bármilyen márkájú és típusú mosógép javításával foglalkozom, legyen akár kisebb meghibásodásról szó vagy akár nagyobb komponensek cseréjérõl!','true');
insert into USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, CATEGORY_ID, DESCRIPTION, APPROVED) values ('feco.jpg','Worker', 'EFC847FA5A386A38FCC9D0573BB87272','feco',3, 'fecofeco@freemail.hu', 'Ferenc Olivér', '06202189920',7, 'Akár televízióról, akár mosógéprõl van szó, hívjon bátran és megnézem mi a gond!','true');
insert into USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, CATEGORY_ID, DESCRIPTION, APPROVED) values ('geri.jpg','Worker', 'EFC847FA5A386A38FCC9D0573BB87272','geri',3, 'geri22@freemail.hu', 'Balatoni Gabi', '06202189920',7, 'Nem megy a tv? Nincsen internet? Írjon rám és pár órán belül már ott is vagyok, ingatlanok kábelezésével is foglalkozom és egyéb apróságokkal!','true');
--47-51
insert into USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, CATEGORY_ID, DESCRIPTION, APPROVED) values ('gergo.jpg','Worker', 'EFC847FA5A386A38FCC9D0573BB87272','gergo',3, 'gergely@freemail.hu', 'Erdei Gergõ', '06202189920',8, 'Házak építésében szerzett 20 éves tapasztalattal várom a leendõ ügyfeleim, ha betonozásra, falépítésre vagy alapozásra van szüksége!','true');
insert into USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, CATEGORY_ID, DESCRIPTION, APPROVED) values ('mate.jpg','Worker', 'EFC847FA5A386A38FCC9D0573BB87272','mate',3, 'mate126@freemail.hu', 'Matek Máté', '06202189920',8, 'Csapatommal vállaljuk házak építését, alapozását, igény esetén tervezését is, forduljon hozzánk bizalommal!','true');
insert into USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, CATEGORY_ID, DESCRIPTION, APPROVED) values ('komuves.jpg','Worker', 'EFC847FA5A386A38FCC9D0573BB87272','komuves',3, 'gyuripapa@freemail.hu', 'Kõmûves Gyuri', '06202189920',8, 'Bármilyen egyedi ötlet megvalósítasat vállalom elõzetes egyeztetés után, gyors munkaidõvel!','true');
insert into USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, CATEGORY_ID, DESCRIPTION, APPROVED) values ('gazsi.jpg','Worker', 'EFC847FA5A386A38FCC9D0573BB87272','gazsi',3, 'gerzson@freemail.hu', 'Gerzson', '06202189920',8, 'Üdv! Az alapvetõ kõmûves munkákon kívül hõszigetelést, burkolást, külsõ festést is vállalunk, ha minket választ az ingatlanja idõtálló lesz évtizedek múlva is!','true');
insert into USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, CATEGORY_ID, DESCRIPTION, APPROVED) values ('peti95.jpg','Worker', 'EFC847FA5A386A38FCC9D0573BB87272','peti95',3, 'peter.95@freemail.hu', 'Kalap Péter', '06306754432',8, 'Falazás, vakolás, nyílászárók behelyezése, ezek csak ízelítõk a széles palettánkról, küldjön üzenetet vagy hívjon minket még ma!','true');

insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('olajcsere', '6000 Ft', 13);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('olajcsere', '6000 Ft', 14);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('olajcsere', '6000 Ft', 15);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('olajcsere', '6000 Ft', 16);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('olajcsere', '6000 Ft', 17);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('olajcsere', '6000 Ft', 18);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('olajcsere', '6000 Ft', 20);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('kerékcsere', '2000/kerék', 13);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('kerékcsere', '2000/kerék', 14);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('kerékcsere', '2000/kerék', 15);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('kerékcsere', '2000/kerék', 18);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('vizsgáztatás', '12500 Ft', 13);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('vizsgáztatás', '12500 Ft', 19);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('vizsgáztatás', '12500 Ft', 18);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('vizsgáztatás', '12500 Ft', 15);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('kipufogó csere', '23000 Ft', 13);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('kipufogó csere', '23000 Ft', 14);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('kipufogó csere', '23000 Ft', 16);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('kipufogó csere', '23000 Ft', 20);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('elektronikai javítás', '8000 Ft +anyag', 13);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('elektronikai javítás', '8000 Ft +anyag', 15);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('elektronikai javítás', '8000 Ft +anyag', 17);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('elektronikai javítás', '8000 Ft +anyag', 18);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('elektronikai javítás', '8000 Ft +anyag', 20);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('motorgenerál', '25000 Ft', 13);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('motorgenerál', '25000 Ft', 14);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('motorgenerál', '25000 Ft', 15);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('motorgenerál', '25000 Ft', 16);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('motorgenerál', '25000 Ft', 18);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('teljeskörû átvizsgálás', '4000 Ft', 13);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('teljeskörû átvizsgálás', '4000 Ft', 14);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('teljeskörû átvizsgálás', '4000 Ft', 15);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('teljeskörû átvizsgálás', '4000 Ft', 17);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('teljeskörû átvizsgálás', '4000 Ft', 20);

insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('teljes kapcsolócsere', '1500/kapcsoló', 21);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('teljes kapcsolócsere', '1500/kapcsoló', 24);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('teljes kapcsolócsere', '1500/kapcsoló', 25);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('teljes kábelezés', '20000-60000 Ft', 21);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('teljes kábelezés', '20000-60000 Ft', 24);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('felmérés', '4000-8000 Ft', 21);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('felmérés', '4000-8000 Ft', 24);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('kiszállási díj', '2000 Ft', 21);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('kiszállási díj', '2000 Ft', 25);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('kiszállási díj', '2000 Ft', 23);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('kiszállási díj', '2000 Ft', 22);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('kiszállási díj', '2000 Ft', 24);

insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('cirkó csere', '50000 Ft', 26);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('cirkó csere', '50000 Ft', 27);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('cirkó csere', '50000 Ft', 28);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('vizesblokk beszerelése', '30000-50000 Ft', 26);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('vizesblokk beszerelése', '30000-50000 Ft', 27);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('vizesblokk beszerelése', '30000-50000 Ft', 28);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('gázcsövek cseréje', '14000+ anyagár', 26);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('kazán beszerelése', '60000 Ft', 26);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('kazán beszerelése', '60000 Ft', 27);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('kazán beszerelése', '60000 Ft', 28);

insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('favágás', '10000-50000 Ft', 30);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('favágás', '10000-50000 Ft', 31);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('füvesítés', '10000-50000 Ft', 30);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('füvesítés', '10000-50000 Ft', 32);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('füvesítés', '10000-50000 Ft', 33);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('kertrendezés', '30000 Ft', 30);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('kertrendezés', '30000 Ft', 33);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('kertészeti karbantartás', '4000 Ft/alkalom', 30);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('kertészeti karbantartás', '4000 Ft/alkalom', 31);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('kertészeti karbantartás', '4000 Ft/alkalom', 32);

insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('ebédlõbútor', '80-100.000 Ft', 34);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('ebédlõbútor', '80-100.000 Ft', 35);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('ebédlõbútor', '80-100.000 Ft', 37);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('konyhabútor', '120-200.000 Ft', 34);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('konyhabútor', '120-200.000 Ft', 36);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('konyhabútor', '120-200.000 Ft', 39);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('kisebb bútorok', '10.000 Ft-tól', 34);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('kisebb bútorok', '10.000 Ft-tól', 35);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('kisebb bútorok', '10.000 Ft-tól', 39);

insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('szobafestés', '30000-80000 Ft', 40);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('mennyezetfestés', '10 ezertõl 50000 Ft-ig', 40);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('mennyezetfestés', '10 ezertõl 50000 Ft-ig', 42);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('teljes falfelújítás', '50000-150000 Ft', 40);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('teljes falfelújítás', '50000-150000 Ft', 42);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('tapétázás', '20000 és 80000 Ft között', 40);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('tapétázás', '20000 és 80000 Ft között', 41);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('tapétázás', '20000 és 80000 Ft között', 42);

insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('mosógép', '10000 Ft +anyag', 43);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('mosógép', '10000 Ft +anyag', 45);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('mikrohullámú sütõ', '4000 Ft +anyag', 43);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('mosogatógép', '10000 Ft +anyag', 43);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('mosogatógép', '10000 Ft +anyag', 44);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('hûtõgép', '10000 Ft +anyag', 43);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('hûtõgép', '10000 Ft +anyag', 45);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('hûtõgép', '10000 Ft +anyag', 46);

insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('betonozás', '50000 Ft', 47);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('alapozás', '50000 Ft', 47);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('falazás', '70000Ft-tól, méretfüggõ', 47);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('falazás', '70000Ft-tól, méretfüggõ', 48);
insert into TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) values ('falazás', '70000Ft-tól, méretfüggõ', 51);


insert into APPOINTMENTS (APPDATE, APPTIME, WORKER_ID,IS_FREE) values (current_timestamp, '14:00-15:00', 13,true);
insert into APPOINTMENTS (APPDATE, APPTIME, WORKER_ID,IS_FREE) values (current_timestamp, '14:00-7:00', 13,true);
insert into APPOINTMENTS (APPDATE, APPTIME, WORKER_ID,IS_FREE) values (current_timestamp, 'délután 4-tõl', 13,true);


insert into MESSAGES (CONTENT,SUBJECT, IS_SEEN, SEND_TIMESTAMP, RECIPIENT_ID, SENDER_ID) values ('Jó napot kívánok! Felvenném önnel a kapcsolatot.','Kapcsolatfelvétel' ,'false', current_timestamp, 13,2);
insert into MESSAGES (CONTENT,SUBJECT,  IS_SEEN, SEND_TIMESTAMP, RECIPIENT_ID, SENDER_ID) values ('Jó napot kívánok! Felvenném önnel a kapcsolatot.', 'Kapcsolatfelvétel' ,'false', current_timestamp, 13,6);
insert into MESSAGES (CONTENT,SUBJECT,  IS_SEEN, SEND_TIMESTAMP, RECIPIENT_ID, SENDER_ID) values ('Jó napot kívánok! Felvenném önnel a kapcsolatot.','Kapcsolatfelvétel' , 'false', current_timestamp, 14,2);
insert into MESSAGES (CONTENT,SUBJECT,  IS_SEEN, SEND_TIMESTAMP, RECIPIENT_ID, SENDER_ID) values ('Jó napot kívánok! Felvenném önnel a kapcsolatot.','Kapcsolatfelvétel' , 'false', '2018-03-21 13:21:32', 15,2);
insert into MESSAGES (CONTENT,SUBJECT,  IS_SEEN, SEND_TIMESTAMP, RECIPIENT_ID, SENDER_ID) values ('Jó napot kívánok! Felvenném önnel a kapcsolatot.','Kapcsolatfelvétel' , 'false', '2018-03-21 13:21:32', 2,13);
insert into MESSAGES (CONTENT,SUBJECT,  IS_SEEN, SEND_TIMESTAMP, RECIPIENT_ID, SENDER_ID) values ('Jó napot kívánok! Felvenném önnel a kapcsolatot.','Kapcsolatfelvétel' , 'false', '2018-03-21 13:21:32', 14,13);
insert into MESSAGES (CONTENT,SUBJECT,  IS_SEEN, SEND_TIMESTAMP, RECIPIENT_ID, SENDER_ID) values ('Jó napot kívánok! Felvenném önnel a kapcsolatot.','Kapcsolatfelvétel' , 'false', '2018-03-21 13:21:32', 13,14);
insert into MESSAGES (CONTENT,SUBJECT,  IS_SEEN, SEND_TIMESTAMP, RECIPIENT_ID, SENDER_ID) values ('Mikorra tudnék idõpontot foglalni egy teljes építkezésre a következõ hónapra várhatóan. ','Idõpontkérés az építkezéshez' , 'true', current_timestamp, 26,2);
insert into MESSAGES (CONTENT, IS_SEEN, SEND_TIMESTAMP, RECIPIENT_ID, SENDER_ID) values ('Jó napot kívánok! Felvenném önnel a kapcsolatot.', 'false', current_timestamp, 15,4);
insert into MESSAGES (CONTENT, IS_SEEN, SEND_TIMESTAMP, RECIPIENT_ID, SENDER_ID) values ('Jó napot kívánok! Felvenném önnel a kapcsolatot.', 'false', current_timestamp, 15,12);
insert into MESSAGES (CONTENT, IS_SEEN, SEND_TIMESTAMP, RECIPIENT_ID, SENDER_ID) values ('Jó napot kívánok! Felvenném önnel a kapcsolatot.', 'false', current_timestamp, 16,12);
insert into MESSAGES (CONTENT, IS_SEEN, SEND_TIMESTAMP, RECIPIENT_ID, SENDER_ID) values ('Jó napot kívánok! Felvenném önnel a kapcsolatot.', 'false', current_timestamp, 17,12);
insert into MESSAGES (CONTENT, IS_SEEN, SEND_TIMESTAMP, RECIPIENT_ID, SENDER_ID) values ('Jó napot kívánok! Felvenném önnel a kapcsolatot.', 'false', current_timestamp, 18,12);
insert into MESSAGES (CONTENT, IS_SEEN, SEND_TIMESTAMP, RECIPIENT_ID, SENDER_ID) values ('Jó napot kívánok! Felvenném önnel a kapcsolatot.', 'false', current_timestamp, 19,12);
insert into MESSAGES (CONTENT, IS_SEEN, SEND_TIMESTAMP, RECIPIENT_ID, SENDER_ID, IS_REPORT) values ('A munkás téves információkat tüntetett fel a profilján, illetve a fizetésnél is problémák voltak, kérem vizsgálják felül!', 'true', '2017-02-21 13:21:32', 13,2,true);
insert into MESSAGES (CONTENT, IS_SEEN, SEND_TIMESTAMP, RECIPIENT_ID, SENDER_ID, IS_REPORT) values ('A munkás téves információkat tüntetett fel a profilján, illetve a fizetésnél is problémák voltak, kérem vizsgálják felül!', 'false', current_timestamp, 19,12,true);


insert into USERS_FAVORITES (USER_ID, WORKER_ID) values (2,14);
insert into USERS_FAVORITES (USER_ID, WORKER_ID) values (2,15);
insert into USERS_FAVORITES (USER_ID, WORKER_ID) values (4,13);
insert into USERS_FAVORITES (USER_ID, WORKER_ID) values (5,17);
insert into USERS_FAVORITES (USER_ID, WORKER_ID) values (6,18);

insert into RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) values ('Jól elvégezte a munkát', '4', current_timestamp, 13,3);
insert into RATINGS (RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) values ('5', current_timestamp, 13,4);
insert into RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) values ('A munka végzése maradéktalanul megtörtént, de fizetés közben egy kis nézeteltérésünk akadt, amit aztán sikerült megoldani ', '3', current_timestamp, 13,2);
insert into RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) values ('Bármikor rábíznám az autómat, nagyon megbízható és készséges ember!', '5', current_timestamp, 13,4);
insert into RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) values ('8 éve hozzá viszem a családi autót, eddig mindig tudott segíteni és nem is drága!', '5', current_timestamp, 14,5);
insert into RATINGS (RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) values ('2', current_timestamp, 15,4);
insert into RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) values ('Megfelelõ, gyors munkavégzés', '1', current_timestamp, 16,4);
insert into RATINGS (RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) values ('3', current_timestamp, 17,5);
insert into RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) values ('10 perc alatt megtörtént a kerékcsere, ajánlott!', '2', current_timestamp, 18,12);
insert into RATINGS (RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) values ('3', current_timestamp, 19,12);
insert into RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) values ('A munkát nem tudta határidõre elvégezni így kénytelen voltam máshova vinni az autómat', '1', current_timestamp, 18,11);
insert into RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) values ('Teljesen alkalmatlan volt a munkára, nem ajánlom senkinek', '1', current_timestamp, 21,3);
insert into RATINGS (RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) values ('5', current_timestamp, 21,4);
insert into RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) values ('Gyorsan kiérekezett és gyorsan el is végezte a munkát!', '5', current_timestamp, 22,2);
insert into RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) values ('Nem voltam teljes mértékben elégedett...', '2', current_timestamp, 22,5);
insert into RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) values ('Az új házunk teljes szerelését rábíztuk, a munkát, nem olcsón, de kiválóan elvégezte.', '4', current_timestamp, 24,6);
insert into RATINGS (RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) values ('1', current_timestamp, 26,2);
insert into RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) values ('Kiváló szakember és nem utolsósorban türelmes is az emberekkel', '5', current_timestamp, 26,4);
insert into RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) values ('Mindent szépen elmagyarázott, nem az ember lehúzására koncentrál, ajánlom õt!', '5', current_timestamp, 26,3);
insert into RATINGS (RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) values ('4', current_timestamp, 27,2);
insert into RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) values ('Nagyon drágán, de végülis elvégezte a ház teljes felújítását, reméljük idõálló is lesz', '3', current_timestamp, 29,8);
insert into RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) values ('Gyors dugulaselhárításra hívtam, lassú duguláselhárítás lett belõle', '2', current_timestamp, 24,2);
insert into RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) values ('Megfelelt mindenben', '4', current_timestamp, 27,10);
insert into RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) values ('10/10', '5', current_timestamp, 27,11);
insert into RATINGS (RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) values ('3', current_timestamp, 30,12);
insert into RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) values ('Évek óta gondozza tavasszal a birtokunkat, akár 10 pontot is adnék rá ha lehet!', '5', current_timestamp, 31,12);
insert into RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) values ('Remek munkát végzett a gyümölcsösben, ajánlom bárkinek!', '1', current_timestamp, 32,12);
insert into RATINGS (RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) values ('2', current_timestamp, 33,12);
insert into RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) values ('Nem értem a negatív értékelést, könnyen megegyeztünk a megbízás részleteirõl.', '4', current_timestamp, 30,4);
insert into RATINGS (RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) values ('1', current_timestamp, 30,11);
insert into RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) values ('Csak az idõmet vesztegette!', '1', current_timestamp, 33,12);
insert into RATINGS (RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) values ('4', current_timestamp, 34,12);
insert into RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) values ('Remek munkát végzett, ajánlom a szekrényeit mindenkinek!', '5', current_timestamp, 34,2);
insert into RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) values ('Teljesen elégedett voltam az általa gyártott bútorokkal.', '5', current_timestamp, 34,6);
insert into RATINGS (RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) values ('5', current_timestamp, 36,7);
insert into RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) values ('Nem voltak túl tartósak a bútorok amiket vettem tõle', '3', current_timestamp, 36,6);
insert into RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) values ('Rendben volt minden.', '4', current_timestamp, 38,2);
insert into RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) values ('Megegyeztünk valamiben, amit nem tudott teljesíteni, viszont nem váltunk el haraggal', '3', current_timestamp, 38,7);
insert into RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) values ('Gyors és pontos volt mindenben', '4', current_timestamp, 40,6);
insert into RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) values ('Jó lett a fal', '4', current_timestamp, 40,2);
insert into RATINGS (RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) values ('3', current_timestamp, 40,8);
insert into RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) values ('A csapatával az egész iskolánkat kifestették és nem is drágán, jó szakemberek!', '5', current_timestamp, 41,3);
insert into RATINGS (RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) values ('4', current_timestamp, 42,3);
insert into RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) values ('Mindig késve érkezett, de a munkájával alapos volt, ezt vegyék figyelembe.', '3', current_timestamp, 42,4);
insert into RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) values ('Nem volt képes csak méregdrágán megjavítani a mosogatógépet', '2', current_timestamp, 43,11);
insert into RATINGS (RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) values ('1', current_timestamp, 43,12);
insert into RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) values ('Fiatalos lendülettel érkezett, majd rövid felmérés után megegyeztünk egymással.', '4', current_timestamp, 44,2);
insert into RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) values ('Tökéletes', '5', current_timestamp, 44,8);
insert into RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) values ('Igaza a mosógépem javíthatatlan volt, de legalább találtam egy biztosan jó szerelõt a továbbiakra!', '5', current_timestamp, 44,5);
insert into RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) values ('Azt hittem, hogy a TV-m tönkrement, amíg nem hívtam. Pár óra múlva jobb volt mint a régi', '5', current_timestamp, 46,2);
insert into RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) values ('Kisebb elõtetõt rendeltem tõlük, 2 héten belül már kész is volt', '5', current_timestamp, 47,3);
insert into RATINGS (RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) values ('3', current_timestamp, 47,11);
insert into RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) values ('A tetõtér beépítésére hívtuk, nagyon elfoglalt volt, de mégis szorított nekünk idõt, ajánlom', '4', current_timestamp, 47,12);
insert into RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) values ('Késve érkezett párszor, de nagyon közvetlen, barátságos szakember!', '4', current_timestamp, 47,7);
insert into RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) values ('A környéken a legjobb kõmûves csapat!', '5', current_timestamp, 47,9);
insert into RATINGS (RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) values ('3', current_timestamp, 47,4);
insert into RATINGS (RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) values ('5', current_timestamp, 48,4);
insert into RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) values ('Nem ajánlom', '2', current_timestamp, 48,7);
insert into RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) values ('Gyorsan készen voltak, látszik, hogy nem az idõhúzás a céljuk!', '5', current_timestamp, 49,2);
insert into RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) values ('A modora hagyott kívánnivalót maga után, de a szakértelme megkérdõjelezhetetlen', '3', current_timestamp, 49,11);
insert into RATINGS (RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) values ('4', current_timestamp, 51,11);
insert into RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) values ('Pontos és egyben alapos is.', '5', current_timestamp, 51,12);
insert into RATINGS (RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) values ('4', current_timestamp, 51,2);

insert into WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) values (13,1);
insert into WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) values (14,1);
insert into WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) values (15,1);
insert into WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) values (16,1);
insert into WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) values (17,1);
insert into WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) values (18,2);
insert into WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) values (18,3);
insert into WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) values (18,7);
insert into WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) values (18,8);
insert into WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) values (19,10);
insert into WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) values (20,22);
insert into WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) values (21,22);
insert into WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) values (22,22);
insert into WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) values (23,30);
insert into WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) values (25,30);
insert into WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) values (24,30);
insert into WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) values (25,28);
insert into WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) values (26,16);
insert into WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) values (27,1);
insert into WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) values (27,24);
insert into WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) values (28,1);
insert into WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) values (29,1);
insert into WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) values (29,11);
insert into WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) values (30,11);
insert into WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) values (30,9);
insert into WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) values (31,9);
insert into WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) values (32,9);
insert into WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) values (32,10);
insert into WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) values (33,17);
insert into WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) values (33,18);
insert into WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) values (34,18);
insert into WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) values (35,10);
insert into WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) values (36,6);
insert into WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) values (36,7);
insert into WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) values (37,9);
insert into WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) values (38,19);
insert into WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) values (38,20);
insert into WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) values (39,24);
insert into WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) values (40,24);
insert into WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) values (40,25);
insert into WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) values (40,22);
insert into WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) values (41,17);
insert into WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) values (42,12);
insert into WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) values (42,13);
insert into WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) values (43,15);
insert into WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) values (44,10);
insert into WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) values (44,11);
insert into WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) values (45,2);
insert into WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) values (45,3);
insert into WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) values (45,4);
insert into WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) values (45,5);
insert into WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) values (45,6);
insert into WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) values (46,6);
insert into WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) values (46,5);
insert into WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) values (47,11);
insert into WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) values (48,11);
insert into WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) values (49,28);
insert into WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) values (49,30);
insert into WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) values (50,24);
insert into WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) values (50,25);
insert into WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) values (51,1);