
INSERT INTO ROLES (ROLE_NAME) VALUES ('ADMIN');
INSERT INTO ROLES (ROLE_NAME) VALUES ('USER');
INSERT INTO ROLES (ROLE_NAME) VALUES ('WORKER');
--1-8
INSERT INTO CATEGORIES (CATEGORY_NAME, PICTURE) VALUES ('Autószerelõ', '1.png');
INSERT INTO CATEGORIES (CATEGORY_NAME, PICTURE) VALUES ('Villanyszerelõ', '2.png');
INSERT INTO CATEGORIES (CATEGORY_NAME, PICTURE) VALUES ('Víz-gáz-fûtésszerelõ', '3.png');
INSERT INTO CATEGORIES (CATEGORY_NAME, PICTURE) VALUES ('Kertész', '4.png');
INSERT INTO CATEGORIES (CATEGORY_NAME, PICTURE) VALUES ('Asztalos', '5.png');
INSERT INTO CATEGORIES (CATEGORY_NAME, PICTURE) VALUES ('Festõ', '6.png');
INSERT INTO CATEGORIES (CATEGORY_NAME, PICTURE) VALUES ('Háztartási gépszerelõ', '7.png');
INSERT INTO CATEGORIES (CATEGORY_NAME, PICTURE) VALUES ('Kõmûves', '8.png');


--1-30
INSERT INTO LOCATIONS (LOCATION_NAME) VALUES ('Budapest');
INSERT INTO LOCATIONS (LOCATION_NAME) VALUES ('Budapest I.');
INSERT INTO LOCATIONS (LOCATION_NAME) VALUES ('Budapest II.');
INSERT INTO LOCATIONS (LOCATION_NAME) VALUES ('Budapest III.');
INSERT INTO LOCATIONS (LOCATION_NAME) VALUES ('Budapest IV.');
INSERT INTO LOCATIONS (LOCATION_NAME) VALUES ('Budapest V.');
INSERT INTO LOCATIONS (LOCATION_NAME) VALUES ('Budapest VI.');
INSERT INTO LOCATIONS (LOCATION_NAME) VALUES ('Budapest VII.');
INSERT INTO LOCATIONS (LOCATION_NAME) VALUES ('Budapest VIII.');
INSERT INTO LOCATIONS (LOCATION_NAME) VALUES ('Budapest IX.');
INSERT INTO LOCATIONS (LOCATION_NAME) VALUES ('Budapest X.');
INSERT INTO LOCATIONS (LOCATION_NAME) VALUES ('Budapest XI.');
INSERT INTO LOCATIONS (LOCATION_NAME) VALUES ('Budapest XII.');
INSERT INTO LOCATIONS (LOCATION_NAME) VALUES ('Budapest XIII.');
INSERT INTO LOCATIONS (LOCATION_NAME) VALUES ('Budapest XIV.');
INSERT INTO LOCATIONS (LOCATION_NAME) VALUES ('Budapest XV.');
INSERT INTO LOCATIONS (LOCATION_NAME) VALUES ('Budapest XVI.');
INSERT INTO LOCATIONS (LOCATION_NAME) VALUES ('Budapest XVII.');
INSERT INTO LOCATIONS (LOCATION_NAME) VALUES ('Budapest XVIII.');
INSERT INTO LOCATIONS (LOCATION_NAME) VALUES ('Budapest XIX.');
INSERT INTO LOCATIONS (LOCATION_NAME) VALUES ('Budapest XX.');
INSERT INTO LOCATIONS (LOCATION_NAME) VALUES ('Budapest XXI.');
INSERT INTO LOCATIONS (LOCATION_NAME) VALUES ('Budapest XXII.');
INSERT INTO LOCATIONS (LOCATION_NAME) VALUES ('Budapest XXIII.');
INSERT INTO LOCATIONS (LOCATION_NAME) VALUES ('Gödöllõ');
INSERT INTO LOCATIONS (LOCATION_NAME) VALUES ('Gyõr');
INSERT INTO LOCATIONS (LOCATION_NAME) VALUES ('Székesfehérvár');
INSERT INTO LOCATIONS (LOCATION_NAME) VALUES ('Miskolc');
INSERT INTO LOCATIONS (LOCATION_NAME) VALUES ('Debrecen');
INSERT INTO LOCATIONS (LOCATION_NAME) VALUES ('Szekszárd');

VARCHAR(32) asd = 'admin';

--1-12
INSERT INTO USERS (USER_TYPE, PASSWORD, USERNAME, ROLE_ID, NAME) VALUES ('Admin', '21232F297A57A5A743894A0E4A801FC3','admin',1, 'Tomi');
INSERT INTO USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, LOCATION_ID, LAST_LOGIN) VALUES ('user.jpg', 'User', 'EFC847FA5A386A38FCC9D0573BB87272','user',2, 'user@user.hu',  'Lee Sándor', '06309987876', 11, '2017-02-21 13:21:32');
INSERT INTO USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, LOCATION_ID) VALUES ('tomi.jpg', 'User', 'EFC847FA5A386A38FCC9D0573BB87272','tomi',2, 'tomi34@gmail.hu',  'Ablakos Tomi', '06309987876',21);
INSERT INTO USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, LOCATION_ID) VALUES ('tibor.jpg', 'User', 'EFC847FA5A386A38FCC9D0573BB87272','tibor',2, 'tibi96@asd.hu',  'Terep Tibor', '06309987876',4);
INSERT INTO USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, LOCATION_ID) VALUES ('patrik.jpg', 'User', 'EFC847FA5A386A38FCC9D0573BB87272','patrik',2, 'pati@invitel.hu',  'Vízi Patrik', '06309987876',6);
INSERT INTO USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, LOCATION_ID) VALUES ('jozsef.jpg', 'User', 'EFC847FA5A386A38FCC9D0573BB87272','jozsef',2, 'jozsi21@gmail.hu', 'Kovács József', '06309987876',7);
INSERT INTO USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, LOCATION_ID) VALUES ('gyorgyi.jpg', 'User', 'EFC847FA5A386A38FCC9D0573BB87272','gyorgyi',2, 'gyorgyike@digi.hu', 'Nyugati Györgyi', '06309987876',8);
INSERT INTO USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, LOCATION_ID) VALUES ('gergely.jpg', 'User', 'EFC847FA5A386A38FCC9D0573BB87272','gergely',2, 'gergo25@digi.hu', 'Leveles Gergely', '06309987876',24);
INSERT INTO USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, LOCATION_ID) VALUES ('erzsi.jpg', 'User', 'EFC847FA5A386A38FCC9D0573BB87272','erzsi',2, 'erzsimama@thome.hu', 'Kovácsné Erzsébet', '06309987876',7);
INSERT INTO USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, LOCATION_ID) VALUES ('balazs.jpg', 'User', 'EFC847FA5A386A38FCC9D0573BB87272','balazs',2, 'balazs@freemail.hu', 'Mérnök Balázs', '06309987876',21);
INSERT INTO USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, LOCATION_ID) VALUES ('anna.jpg', 'User', 'EFC847FA5A386A38FCC9D0573BB87272','anna',2, 'anna.kiss@gmail.hu', 'Kiss Anna', '06309987876',10);
INSERT INTO USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, LOCATION_ID) VALUES ('adam.jpg', 'User', 'EFC847FA5A386A38FCC9D0573BB87272','adam',2, 'adamszalai@citromail.hu', 'Szalai Ádám', '06309987876',26);

--13-20
INSERT INTO USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, CATEGORY_ID, DESCRIPTION, LAST_LOGIN, APPROVED) VALUES ('kriszti1992.jpg', 'Worker', 'EFC847FA5A386A38FCC9D0573BB87272','kriszti1992',3, 'kriszti92@gmail.com', 'Kriszti', '062022126',1, 'Foglalkozom régi illetve újabb évjáratú autók szervizelésével, szeretettel várom a mûhelyemben, illetve kiszállásra is van lehetõség!', '2017-02-21 13:21:32','true');
INSERT INTO USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, CATEGORY_ID, DESCRIPTION, APPROVED) VALUES ('ferenc.jpg', 'Worker', 'EFC847FA5A386A38FCC9D0573BB87272','ferenc',3, 'ferenc1995@gmail.com', 'Ferenc Ajtós', '06302218787',1, 'Üdv! Fiatalos, de tapasztalt csapat várja Önt szervizünkben Budapesten, a fõ profilunk a japán illetve a koreai gyártmányú autók javítása.','true');
INSERT INTO USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, CATEGORY_ID, DESCRIPTION, APPROVED) VALUES ('javito.jpg', 'Worker', 'EFC847FA5A386A38FCC9D0573BB87272','javito',3, 'javitok@gmail.com', 'Javító Jani', '06202233236',1, 'Közel 20 éve foglalkozom BMW, Mercedes, Audi, Opel és egyéb német gyártmányú autók szervizelésével, forduljon bizalommal hozzánk!','true');
INSERT INTO USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, CATEGORY_ID, DESCRIPTION, APPROVED) VALUES ('kerekes.jpg', 'Worker', 'EFC847FA5A386A38FCC9D0573BB87272','kerekes',3, 'kerek@gmail.com', 'Kerekes Géza', '06202233236',1, 'Gumis illetve kerékjavító szervizembe várom a vendégeket, bármilyen típusú autóval/tehergépjármûvel foglalkozunk!','true');
INSERT INTO USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, CATEGORY_ID, DESCRIPTION, APPROVED) VALUES ('tamas.jpg', 'Worker', 'EFC847FA5A386A38FCC9D0573BB87272','tamas',3, 'tamas13@gmail.com', 'Járvás Tamás', '06709498873',1, 'Nagy kapacitással rendelkezõ szervizemben várom Budapest szívében!','true');
INSERT INTO USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, CATEGORY_ID, DESCRIPTION, APPROVED) VALUES ('autos.jpg', 'Worker', 'EFC847FA5A386A38FCC9D0573BB87272','autos',3, 'autospeti@gmail.com', 'Autós Péter', '062022556236',1, 'Motorok, illetve kisteherautók szervizelése is megoldhato nálunk, küldjön üzenetet!','true');
INSERT INTO USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, CATEGORY_ID, DESCRIPTION, APPROVED) VALUES ('erika778.jpg', 'Worker', 'EFC847FA5A386A38FCC9D0573BB87272','erika778',3, 'erika778@asd.hu', 'Nagy Erika', '06202126',1, 'Foglaljon idõpontot és autóját akár pár órán belül megvizsgáljuk, a felmérés után az árlistát figyelembe véve kap tõlünk ajánlatot!','true');
INSERT INTO USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, CATEGORY_ID, DESCRIPTION, APPROVED) VALUES ('barat.jpg', 'Worker', 'EFC847FA5A386A38FCC9D0573BB87272','barat',3, 'barattamas@gmail.com', 'Barát Tamás', '062022556236',1, 'Alvázjavításra nem talál jobb embert nálam, vegye fel a kapcsolatot!','true');
--21-25
INSERT INTO USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, CATEGORY_ID, DESCRIPTION, APPROVED) VALUES ('alma112.jpg','Worker', 'EFC847FA5A386A38FCC9D0573BB87272','alma112',3, 'almaalma@citromail.hu', 'Kovács Alma', '06708765657',2, 'Üdvözloö! Kedvezményes kiszállási díjjal állok rendelkezésére, az árlistámon mindent megtalál, további információkért küldjön üzenetet!','true');
INSERT INTO USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, CATEGORY_ID, DESCRIPTION, APPROVED) VALUES ('peter.jpg','Worker', 'EFC847FA5A386A38FCC9D0573BB87272','peter',3, 'peternagy@citromail.hu', 'Nagy Péter', '06708765657',2, '20 éve villanyszereléssel foglalkozom, a felmérés után képességeimhez mérten bármit meg tudok valósitani!','true');
INSERT INTO USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, CATEGORY_ID, DESCRIPTION, APPROVED) VALUES ('laci.jpg','Worker', 'EFC847FA5A386A38FCC9D0573BB87272','laci',3, 'laci1993@citromail.hu', 'László', '06708765657',2, 'Bármilyen villanyszerelési, illetve épületgépészeti munkával keressen bizalommal, velem a leggyorsabban megvalósíthatja terveit! ','true');
INSERT INTO USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, CATEGORY_ID, DESCRIPTION, APPROVED) VALUES ('andris5.jpg','Worker', 'EFC847FA5A386A38FCC9D0573BB87272','andris5',3, 'andris1956@citromail.hu', 'Alma András', '067065657',2, 'Új kapcsolók, dugaljak, lámpák felszerelése? Az ilyen gyors munkákat kedvezményes áron végzem el, tudva milyen gyorsan szükség lehet az ilyen apróságokra! ','true');
INSERT INTO USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, CATEGORY_ID, DESCRIPTION, APPROVED) VALUES ('feri22.jpg','Worker', 'EFC847FA5A386A38FCC9D0573BB87272','feri22',3, 'ferenc@freemail.hu', 'Szegedi Ferenc', '06708766757',2, 'Nagyobb intézmények, ingatlanok teljeskörû villanyszerelésével is foglalkozom, ilyen munka esetén üzenetben keressen fel mindenképp! ','true');
--26-29
INSERT INTO USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, CATEGORY_ID, DESCRIPTION, APPROVED) VALUES ('aladar.jpg','Worker', 'EFC847FA5A386A38FCC9D0573BB87272','aladar',3, 'aladar47@freemail.hu', 'Arany Aladár', '06708766757',3, 'Víz-gáz és fûtéssel is foglalkozom, az árlistán ilyen jellegû feladatokat is megtalál. Leggyakrabban családi házak, illetve új építésû ingatlanok szereléséhez/építkezéséhez hívnak, hívjon Ön is!','true');
INSERT INTO USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, CATEGORY_ID, DESCRIPTION, APPROVED) VALUES ('istvan.jpg','Worker', 'EFC847FA5A386A38FCC9D0573BB87272','istvan',3, 'kovacs.istvan@freemail.hu', 'Kovács István', '06708766757',3, '30 éves tapasztalattal rendelkezem, egészen az egyszerû dugulástól a teljes vizesblokk beszereléséig. Ne feledje, ha vízszerelés, akkor Kovács István!','true');
INSERT INTO USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, CATEGORY_ID, DESCRIPTION, APPROVED) VALUES ('bence.jpg','Worker', 'EFC847FA5A386A38FCC9D0573BB87272','bence',3, 'bence.kiss@freemail.hu', 'Kiss Bence', '06708766757',3, 'Fiatalos, gyors munkavégzés, kis felár esetén villámfelméréssel, írjon rám :) !','true');
INSERT INTO USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, CATEGORY_ID, DESCRIPTION, APPROVED) VALUES ('denes.jpg','Worker', 'EFC847FA5A386A38FCC9D0573BB87272','denes',3, 'denes77@citromail.hu', 'Horváth Dénes', '06207896765',3, 'Fûtésrendszer a fõ szakterületem, ezek közül gázos, elektromos, de akár fatüzeléses megoldásokat is könnyedén szerelek/építek!','true');

--30-33
INSERT INTO USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, CATEGORY_ID, DESCRIPTION, APPROVED) VALUES ('lilla12.jpg','Worker', 'EFC847FA5A386A38FCC9D0573BB87272','lilla12',3, 'lilla12@hotmail.hu', 'Fekete Lilla', '0620212229',4, 'Ha szimpatikus, de ugyanakkor tapasztalt munkavállalót keres, keressen fel. Nem csak virágoskertbe!','true');
INSERT INTO USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, CATEGORY_ID, DESCRIPTION, APPROVED) VALUES ('kerteszferi.jpg','Worker', 'EFC847FA5A386A38FCC9D0573BB87272','kerteszferi',3, 'kerteszferenc@hotmail.hu', 'Kertész Ferenc', '06304567676',4, 'Faiskolában dolgoztam 10 évig, gyümölcsöskertek gondozásával, erdészeti munkákkal foglalkoznék, kisebb munkaként akár favágással is!','true');
INSERT INTO USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, CATEGORY_ID, DESCRIPTION, APPROVED) VALUES ('sandor.jpg','Worker', 'EFC847FA5A386A38FCC9D0573BB87272','sandor',3, 'sandor@hotmail.hu', 'Földes Sándor', '0620212229',4, 'Virágoskertek illetve akár zöldségeskertek karbantartásával kapcsolatban keressen nyugodtan!','true');
INSERT INTO USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, CATEGORY_ID, DESCRIPTION, APPROVED) VALUES ('antal.jpg','Worker', 'EFC847FA5A386A38FCC9D0573BB87272','antal',3, 'antalj40@hotmail.hu', 'Jónás Antal', '06704453434',4, '30 éves tapasztalattal rendelkezõ kertész keres családi házat vagy birtokot, amit felügyelhet.','true');
--34-39
INSERT INTO USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, CATEGORY_ID, DESCRIPTION, APPROVED) VALUES ('girl126.jpg','Worker', 'EFC847FA5A386A38FCC9D0573BB87272','girl126',3, 'erzsike@asd.hu', 'Erzsébet', '0620222128',5, 'Egyedi bútorok és háztartási eszközök készítésével tervezésével foglalkozunk, ha van bármilyen ötlete vegye fel a kapcsolatot és megnézzük mit tehetünk!','true');
INSERT INTO USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, CATEGORY_ID, DESCRIPTION, APPROVED) VALUES ('gabor.jpg','Worker', 'EFC847FA5A386A38FCC9D0573BB87272','gabor',3, 'gabor@gmail.hu', 'Takács Gábor', '067210101',5, 'Kisebb bútorok készítésével foglalkozom, csak a legjobb minõségû alapanyagokból!','true');
INSERT INTO USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, CATEGORY_ID, DESCRIPTION, APPROVED) VALUES ('karoly.jpg','Worker', 'EFC847FA5A386A38FCC9D0573BB87272','karoly',3, 'karoly@freemail.hu', 'Tölgyes Károly', '0688799867',5, 'Üdvözlöm! Bármilyen faipari termék elõlállítását ránk bízhatja a gerendától egészen a hajópadlóig!','true');
INSERT INTO USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, CATEGORY_ID, DESCRIPTION, APPROVED) VALUES ('lajos.jpg','Worker', 'EFC847FA5A386A38FCC9D0573BB87272','lajos',3, 'lajos@gmail.hu', 'Fehér Lajos', '0620222128',5, 'Fa asztalok, székek egyedi megrendelésre, limitált példányszámban, küldjön üzenetet árajánlatra!','true');
INSERT INTO USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, CATEGORY_ID, DESCRIPTION, APPROVED) VALUES ('marcell.jpg','Worker', 'EFC847FA5A386A38FCC9D0573BB87272','marcell',3, 'marcell@gmail.hu', 'Marcell', '0620232221',5, '30 éves tapasztalattal rendelkezõ asztalosmester várja a hívását.','true');
INSERT INTO USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, CATEGORY_ID, DESCRIPTION, APPROVED) VALUES ('lali.jpg','Worker', 'EFC847FA5A386A38FCC9D0573BB87272','lali',3, 'laliapu@gmail.hu', 'Gerendás Lajos', '0620232221',5, 'Mûhelyemben bármilyen szekrény, gardróbszekrény, konyhabútor, nappali bútor vagy komód készítését vállalom!','true');

--40-42
INSERT INTO USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, CATEGORY_ID, DESCRIPTION, APPROVED) VALUES ('szilvi.jpg','Worker', 'EFC847FA5A386A38FCC9D0573BB87272','szilvi',3, 'szilvi79@freemail.hu', 'Barát Szilvia', '06202120',6, 'Szobafestés most kedvezményes áron, a hely méretétõl függõen, akár mennyiségi kedvezménnyel is, keressen bátran!','true');
INSERT INTO USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, CATEGORY_ID, DESCRIPTION) VALUES ('festo.jpg','Worker', 'EFC847FA5A386A38FCC9D0573BB87272','festo',3, 'oli55@freemail.hu', 'Kocka Olivér', '06202189920',6, 'Az anyag miatt se aggódjon, a festék keverését én magam végzem minõségi alapanyagokból, évtizedes szakértelemmel!');
INSERT INTO USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, CATEGORY_ID, DESCRIPTION, APPROVED) VALUES ('joe.jpg','Worker', 'EFC847FA5A386A38FCC9D0573BB87272','joe',3, 'joe21@freemail.hu', 'Barna Jónás', '06202189920',6, 'Mûvészi képek festésével is foglalkoztam pár évig, így akár gyermekszobai rajzokat is festhetek egyedi ötlet alapján.','true');
--43-46
INSERT INTO USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, CATEGORY_ID, DESCRIPTION, APPROVED) VALUES ('david.jpg','Worker', 'EFC847FA5A386A38FCC9D0573BB87272','david',3, 'david33@freemail.hu', 'Budai Dávid', '06202189920',7, 'Kedvezõ kiszállási díjjal vállalom mosógépek, hûtõgépek, mosogatógépek szervizelését, keressen üzenetben ajánlatért!','true');
INSERT INTO USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, CATEGORY_ID, DESCRIPTION, APPROVED) VALUES ('jani.jpg','Worker', 'EFC847FA5A386A38FCC9D0573BB87272','jani',3, 'jancsika@freemail.hu', 'Pesti János', '06202189920',7, 'Pesti János, a mosógépek szakértõje: bármilyen márkájú és típusú mosógép javításával foglalkozom, legyen akár kisebb meghibásodásról szó vagy akár nagyobb komponensek cseréjérõl!','true');
INSERT INTO USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, CATEGORY_ID, DESCRIPTION, APPROVED) VALUES ('feco.jpg','Worker', 'EFC847FA5A386A38FCC9D0573BB87272','feco',3, 'fecofeco@freemail.hu', 'Ferenc Olivér', '06202189920',7, 'Akár televízióról, akár mosógéprõl van szó, hívjon bátran és megnézem mi a gond!','true');
INSERT INTO USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, CATEGORY_ID, DESCRIPTION, APPROVED) VALUES ('geri.jpg','Worker', 'EFC847FA5A386A38FCC9D0573BB87272','geri',3, 'geri22@freemail.hu', 'Balatoni Gabi', '06202189920',7, 'Nem megy a tv? Nincsen internet? Írjon rám és pár órán belül már ott is vagyok, ingatlanok kábelezésével is foglalkozom és egyéb apróságokkal!','true');
--47-51
INSERT INTO USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, CATEGORY_ID, DESCRIPTION, APPROVED) VALUES ('gergo.jpg','Worker', 'EFC847FA5A386A38FCC9D0573BB87272','gergo',3, 'gergely@freemail.hu', 'Erdei Gergõ', '06202189920',8, 'Házak építésében szerzett 20 éves tapasztalattal várom a leendõ ügyfeleim, ha betonozásra, falépítésre vagy alapozásra van szüksége!','true');
INSERT INTO USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, CATEGORY_ID, DESCRIPTION, APPROVED) VALUES ('mate.jpg','Worker', 'EFC847FA5A386A38FCC9D0573BB87272','mate',3, 'mate126@freemail.hu', 'Matek Máté', '06202189920',8, 'Csapatommal vállaljuk házak építését, alapozását, igény esetén tervezését is, forduljon hozzánk bizalommal!','true');
INSERT INTO USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, CATEGORY_ID, DESCRIPTION, APPROVED) VALUES ('komuves.jpg','Worker', 'EFC847FA5A386A38FCC9D0573BB87272','komuves',3, 'gyuripapa@freemail.hu', 'Kõmûves Gyuri', '06202189920',8, 'Bármilyen egyedi ötlet megvalósítasat vállalom elõzetes egyeztetés után, gyors munkaidõvel!','true');
INSERT INTO USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, CATEGORY_ID, DESCRIPTION, APPROVED) VALUES ('gazsi.jpg','Worker', 'EFC847FA5A386A38FCC9D0573BB87272','gazsi',3, 'gerzson@freemail.hu', 'Gerzson', '06202189920',8, 'Üdv! Az alapvetõ kõmûves munkákon kívül hõszigetelést, burkolást, külsõ festést is vállalunk, ha minket választ az ingatlanja idõtálló lesz évtizedek múlva is!','true');
INSERT INTO USERS (IMAGE, USER_TYPE, PASSWORD, USERNAME, ROLE_ID, EMAIL, NAME, PHONE_NUM, CATEGORY_ID, DESCRIPTION, APPROVED) VALUES ('peti95.jpg','Worker', 'EFC847FA5A386A38FCC9D0573BB87272','peti95',3, 'peter.95@freemail.hu', 'Kalap Péter', '06306754432',8, 'Falazás, vakolás, nyílászárók behelyezése, ezek csak ízelítõk a széles palettánkról, küldjön üzenetet vagy hívjon minket még ma!','true');

INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('olajcsere', '6000 Ft', 13);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('olajcsere', '6000 Ft', 14);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('olajcsere', '6000 Ft', 15);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('olajcsere', '6000 Ft', 16);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('olajcsere', '6000 Ft', 17);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('olajcsere', '6000 Ft', 18);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('olajcsere', '6000 Ft', 20);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('kerékcsere', '2000/kerék', 13);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('kerékcsere', '2000/kerék', 14);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('kerékcsere', '2000/kerék', 15);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('kerékcsere', '2000/kerék', 18);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('vizsgáztatás', '12500 Ft', 13);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('vizsgáztatás', '12500 Ft', 19);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('vizsgáztatás', '12500 Ft', 18);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('vizsgáztatás', '12500 Ft', 15);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('kipufogó csere', '23000 Ft', 13);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('kipufogó csere', '23000 Ft', 14);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('kipufogó csere', '23000 Ft', 16);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('kipufogó csere', '23000 Ft', 20);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('elektronikai javítás', '8000 Ft +anyag', 13);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('elektronikai javítás', '8000 Ft +anyag', 15);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('elektronikai javítás', '8000 Ft +anyag', 17);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('elektronikai javítás', '8000 Ft +anyag', 18);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('elektronikai javítás', '8000 Ft +anyag', 20);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('motorgenerál', '25000 Ft', 13);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('motorgenerál', '25000 Ft', 14);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('motorgenerál', '25000 Ft', 15);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('motorgenerál', '25000 Ft', 16);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('motorgenerál', '25000 Ft', 18);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('teljeskörû átvizsgálás', '4000 Ft', 13);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('teljeskörû átvizsgálás', '4000 Ft', 14);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('teljeskörû átvizsgálás', '4000 Ft', 15);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('teljeskörû átvizsgálás', '4000 Ft', 17);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('teljeskörû átvizsgálás', '4000 Ft', 20);

INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('teljes kapcsolócsere', '1500/kapcsoló', 21);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('teljes kapcsolócsere', '1500/kapcsoló', 24);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('teljes kapcsolócsere', '1500/kapcsoló', 25);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('teljes kábelezés', '20000-60000 Ft', 21);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('teljes kábelezés', '20000-60000 Ft', 24);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('felmérés', '4000-8000 Ft', 21);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('felmérés', '4000-8000 Ft', 24);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('kiszállási díj', '2000 Ft', 21);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('kiszállási díj', '2000 Ft', 25);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('kiszállási díj', '2000 Ft', 23);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('kiszállási díj', '2000 Ft', 22);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('kiszállási díj', '2000 Ft', 24);

INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('cirkó csere', '50000 Ft', 26);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('cirkó csere', '50000 Ft', 27);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('cirkó csere', '50000 Ft', 28);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('vizesblokk beszerelése', '30000-50000 Ft', 26);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('vizesblokk beszerelése', '30000-50000 Ft', 27);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('vizesblokk beszerelése', '30000-50000 Ft', 28);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('gázcsövek cseréje', '14000+ anyagár', 26);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('kazán beszerelése', '60000 Ft', 26);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('kazán beszerelése', '60000 Ft', 27);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('kazán beszerelése', '60000 Ft', 28);

INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('favágás', '10000-50000 Ft', 30);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('favágás', '10000-50000 Ft', 31);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('füvesítés', '10000-50000 Ft', 30);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('füvesítés', '10000-50000 Ft', 32);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('füvesítés', '10000-50000 Ft', 33);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('kertrendezés', '30000 Ft', 30);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('kertrendezés', '30000 Ft', 33);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('kertészeti karbantartás', '4000 Ft/alkalom', 30);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('kertészeti karbantartás', '4000 Ft/alkalom', 31);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('kertészeti karbantartás', '4000 Ft/alkalom', 32);

INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('ebédlõbútor', '80-100.000 Ft', 34);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('ebédlõbútor', '80-100.000 Ft', 35);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('ebédlõbútor', '80-100.000 Ft', 37);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('konyhabútor', '120-200.000 Ft', 34);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('konyhabútor', '120-200.000 Ft', 36);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('konyhabútor', '120-200.000 Ft', 39);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('kisebb bútorok', '10.000 Ft-tól', 34);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('kisebb bútorok', '10.000 Ft-tól', 35);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('kisebb bútorok', '10.000 Ft-tól', 39);

INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('szobafestés', '30000-80000 Ft', 40);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('mennyezetfestés', '10 ezertõl 50000 Ft-ig', 40);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('mennyezetfestés', '10 ezertõl 50000 Ft-ig', 42);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('teljes falfelújítás', '50000-150000 Ft', 40);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('teljes falfelújítás', '50000-150000 Ft', 42);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('tapétázás', '20000 és 80000 Ft között', 40);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('tapétázás', '20000 és 80000 Ft között', 41);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('tapétázás', '20000 és 80000 Ft között', 42);

INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('mosógép', '10000 Ft +anyag', 43);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('mosógép', '10000 Ft +anyag', 45);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('mikrohullámú sütõ', '4000 Ft +anyag', 43);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('mosogatógép', '10000 Ft +anyag', 43);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('mosogatógép', '10000 Ft +anyag', 44);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('hûtõgép', '10000 Ft +anyag', 43);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('hûtõgép', '10000 Ft +anyag', 45);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('hûtõgép', '10000 Ft +anyag', 46);

INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('betonozás', '50000 Ft', 47);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('alapozás', '50000 Ft', 47);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('falazás', '70000Ft-tól, méretfüggõ', 47);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('falazás', '70000Ft-tól, méretfüggõ', 48);
INSERT INTO TASKS (TASK_NAME, TASK_PRICES, WORKER_ID) VALUES ('falazás', '70000Ft-tól, méretfüggõ', 51);


INSERT INTO APPOINTMENTS (APPDATE, APPTIME, WORKER_ID,IS_FREE) VALUES (current_timestamp, '14:00-15:00', 13,true);
INSERT INTO APPOINTMENTS (APPDATE, APPTIME, WORKER_ID,IS_FREE) VALUES (current_timestamp, '14:00-7:00', 13,true);
INSERT INTO APPOINTMENTS (APPDATE, APPTIME, WORKER_ID,IS_FREE) VALUES (current_timestamp, 'délután 4-tõl', 13,true);


INSERT INTO MESSAGES (CONTENT,SUBJECT, IS_SEEN, SEND_TIMESTAMP, RECIPIENT_ID, SENDER_ID) VALUES ('Jó napot kívánok! Felvenném önnel a kapcsolatot.','Kapcsolatfelvétel' ,'false', current_timestamp, 13,2);
INSERT INTO MESSAGES (CONTENT,SUBJECT,  IS_SEEN, SEND_TIMESTAMP, RECIPIENT_ID, SENDER_ID) VALUES ('Jó napot kívánok! Felvenném önnel a kapcsolatot.', 'Kapcsolatfelvétel' ,'false', current_timestamp, 13,6);
INSERT INTO MESSAGES (CONTENT,SUBJECT,  IS_SEEN, SEND_TIMESTAMP, RECIPIENT_ID, SENDER_ID) VALUES ('Jó napot kívánok! Felvenném önnel a kapcsolatot.','Kapcsolatfelvétel' , 'false', current_timestamp, 14,2);
INSERT INTO MESSAGES (CONTENT,SUBJECT,  IS_SEEN, SEND_TIMESTAMP, RECIPIENT_ID, SENDER_ID) VALUES ('Jó napot kívánok! Felvenném önnel a kapcsolatot.','Kapcsolatfelvétel' , 'false', '2018-02-21 13:21:32', 15,2);
INSERT INTO MESSAGES (CONTENT,SUBJECT,  IS_SEEN, SEND_TIMESTAMP, RECIPIENT_ID, SENDER_ID) VALUES ('Jó napot kívánok! Felvenném önnel a kapcsolatot.','Kapcsolatfelvétel' , 'false', '2018-02-21 13:21:32', 2,13);
INSERT INTO MESSAGES (CONTENT,SUBJECT,  IS_SEEN, SEND_TIMESTAMP, RECIPIENT_ID, SENDER_ID) VALUES ('Jó napot kívánok! Felvenném önnel a kapcsolatot.','Kapcsolatfelvétel' , 'false', '2018-02-21 13:21:32', 14,13);
INSERT INTO MESSAGES (CONTENT,SUBJECT,  IS_SEEN, SEND_TIMESTAMP, RECIPIENT_ID, SENDER_ID) VALUES ('Jó napot kívánok! Felvenném önnel a kapcsolatot.','Kapcsolatfelvétel' , 'false', '2018-02-21 13:21:32', 13,14);
INSERT INTO MESSAGES (CONTENT,SUBJECT,  IS_SEEN, SEND_TIMESTAMP, RECIPIENT_ID, SENDER_ID) VALUES ('Mikorra tudnék idõpontot foglalni egy teljes építkezésre a következõ hónapra várhatóan. ','Idõpontkérés az építkezéshez' , 'true', current_timestamp, 26,2);
INSERT INTO MESSAGES (CONTENT, IS_SEEN, SEND_TIMESTAMP, RECIPIENT_ID, SENDER_ID) VALUES ('Jó napot kívánok! Felvenném önnel a kapcsolatot.', 'false', current_timestamp, 15,4);
INSERT INTO MESSAGES (CONTENT, IS_SEEN, SEND_TIMESTAMP, RECIPIENT_ID, SENDER_ID) VALUES ('Jó napot kívánok! Felvenném önnel a kapcsolatot.', 'false', current_timestamp, 15,12);
INSERT INTO MESSAGES (CONTENT, IS_SEEN, SEND_TIMESTAMP, RECIPIENT_ID, SENDER_ID) VALUES ('Jó napot kívánok! Felvenném önnel a kapcsolatot.', 'false', current_timestamp, 16,12);
INSERT INTO MESSAGES (CONTENT, IS_SEEN, SEND_TIMESTAMP, RECIPIENT_ID, SENDER_ID) VALUES ('Jó napot kívánok! Felvenném önnel a kapcsolatot.', 'false', current_timestamp, 17,12);
INSERT INTO MESSAGES (CONTENT, IS_SEEN, SEND_TIMESTAMP, RECIPIENT_ID, SENDER_ID) VALUES ('Jó napot kívánok! Felvenném önnel a kapcsolatot.', 'false', current_timestamp, 18,12);
INSERT INTO MESSAGES (CONTENT, IS_SEEN, SEND_TIMESTAMP, RECIPIENT_ID, SENDER_ID) VALUES ('Jó napot kívánok! Felvenném önnel a kapcsolatot.', 'false', current_timestamp, 19,12);
INSERT INTO MESSAGES (CONTENT, IS_SEEN, SEND_TIMESTAMP, RECIPIENT_ID, SENDER_ID, IS_REPORT) VALUES ('A munkás téves információkat tüntetett fel a profilján, illetve a fizetésnél is problémák voltak, kérem vizsgálják felül!', 'false', current_timestamp, 19,12,true);

INSERT INTO USERS_FAVORITES (USER_ID, WORKER_ID) VALUES (2,13);
INSERT INTO USERS_FAVORITES (USER_ID, WORKER_ID) VALUES (2,14);
INSERT INTO USERS_FAVORITES (USER_ID, WORKER_ID) VALUES (2,15);
INSERT INTO USERS_FAVORITES (USER_ID, WORKER_ID) VALUES (3,13);
INSERT INTO USERS_FAVORITES (USER_ID, WORKER_ID) VALUES (5,17);
INSERT INTO USERS_FAVORITES (USER_ID, WORKER_ID) VALUES (6,18);

INSERT INTO RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) VALUES ('Jól elvégezte a munkát', '4', current_timestamp, 13,3);
INSERT INTO RATINGS (RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) VALUES ('5', current_timestamp, 13,4);
INSERT INTO RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) VALUES ('A munka végzése maradéktalanul megtörtént, de fizetés közben egy kis nézeteltérésünk akadt, amit aztán sikerült megoldani ', '3', current_timestamp, 13,2);
INSERT INTO RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) VALUES ('Bármikor rábíznám az autómat, nagyon megbízható és készséges ember!', '5', current_timestamp, 13,4);
INSERT INTO RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) VALUES ('8 éve hozzá viszem a családi autót, eddig mindig tudott segíteni és nem is drága!', '5', current_timestamp, 14,5);
INSERT INTO RATINGS (RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) VALUES ('2', current_timestamp, 15,4);
INSERT INTO RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) VALUES ('Megfelelõ, gyors munkavégzés', '1', current_timestamp, 16,4);
INSERT INTO RATINGS (RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) VALUES ('3', current_timestamp, 17,5);
INSERT INTO RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) VALUES ('10 perc alatt megtörtént a kerékcsere, ajánlott!', '2', current_timestamp, 18,12);
INSERT INTO RATINGS (RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) VALUES ('3', current_timestamp, 19,12);
INSERT INTO RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) VALUES ('A munkát nem tudta határidõre elvégezni így kénytelen voltam máshova vinni az autómat', '1', current_timestamp, 18,11);
INSERT INTO RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) VALUES ('Teljesen alkalmatlan volt a munkára, nem ajánlom senkinek', '1', current_timestamp, 21,3);
INSERT INTO RATINGS (RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) VALUES ('5', current_timestamp, 21,4);
INSERT INTO RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) VALUES ('Gyorsan kiérekezett és gyorsan el is végezte a munkát!', '5', current_timestamp, 22,2);
INSERT INTO RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) VALUES ('Nem voltam teljes mértékben elégedett...', '2', current_timestamp, 22,5);
INSERT INTO RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) VALUES ('Az új házunk teljes szerelését rábíztuk, a munkát, nem olcsón, de kiválóan elvégezte.', '4', current_timestamp, 24,6);
INSERT INTO RATINGS (RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) VALUES ('1', current_timestamp, 26,2);
INSERT INTO RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) VALUES ('Kiváló szakember és nem utolsósorban türelmes is az emberekkel', '5', current_timestamp, 26,4);
INSERT INTO RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) VALUES ('Mindent szépen elmagyarázott, nem az ember lehúzására koncentrál, ajánlom õt!', '5', current_timestamp, 26,3);
INSERT INTO RATINGS (RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) VALUES ('4', current_timestamp, 27,2);
INSERT INTO RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) VALUES ('Nagyon drágán, de végülis elvégezte a ház teljes felújítását, reméljük idõálló is lesz', '3', current_timestamp, 29,8);
INSERT INTO RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) VALUES ('Gyors dugulaselhárításra hívtam, lassú duguláselhárítás lett belõle', '2', current_timestamp, 24,2);
INSERT INTO RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) VALUES ('Megfelelt mindenben', '4', current_timestamp, 27,10);
INSERT INTO RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) VALUES ('10/10', '5', current_timestamp, 27,11);
INSERT INTO RATINGS (RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) VALUES ('3', current_timestamp, 30,12);
INSERT INTO RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) VALUES ('Évek óta gondozza tavasszal a birtokunkat, akár 10 pontot is adnék rá ha lehet!', '5', current_timestamp, 31,12);
INSERT INTO RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) VALUES ('Remek munkát végzett a gyümölcsösben, ajánlom bárkinek!', '1', current_timestamp, 32,12);
INSERT INTO RATINGS (RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) VALUES ('2', current_timestamp, 33,12);
INSERT INTO RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) VALUES ('Nem értem a negatív értékelést, könnyen megegyeztünk a megbízás részleteirõl.', '4', current_timestamp, 30,4);
INSERT INTO RATINGS (RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) VALUES ('1', current_timestamp, 30,11);
INSERT INTO RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) VALUES ('Csak az idõmet vesztegette!', '1', current_timestamp, 33,12);
INSERT INTO RATINGS (RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) VALUES ('4', current_timestamp, 34,12);
INSERT INTO RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) VALUES ('Remek munkát végzett, ajánlom a szekrényeit mindenkinek!', '5', current_timestamp, 34,2);
INSERT INTO RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) VALUES ('Teljesen elégedett voltam az általa gyártott bútorokkal.', '5', current_timestamp, 34,6);
INSERT INTO RATINGS (RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) VALUES ('5', current_timestamp, 36,7);
INSERT INTO RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) VALUES ('Nem voltak túl tartósak a bútorok amiket vettem tõle', '3', current_timestamp, 36,6);
INSERT INTO RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) VALUES ('Rendben volt minden.', '4', current_timestamp, 38,2);
INSERT INTO RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) VALUES ('Megegyeztünk valamiben, amit nem tudott teljesíteni, viszont nem váltunk el haraggal', '3', current_timestamp, 38,7);
INSERT INTO RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) VALUES ('Gyors és pontos volt mindenben', '4', current_timestamp, 40,6);
INSERT INTO RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) VALUES ('Jó lett a fal', '4', current_timestamp, 40,2);
INSERT INTO RATINGS (RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) VALUES ('3', current_timestamp, 40,8);
INSERT INTO RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) VALUES ('A csapatával az egész iskolánkat kifestették és nem is drágán, jó szakemberek!', '5', current_timestamp, 41,3);
INSERT INTO RATINGS (RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) VALUES ('4', current_timestamp, 42,3);
INSERT INTO RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) VALUES ('Mindig késve érkezett, de a munkájával alapos volt, ezt vegyék figyelembe.', '3', current_timestamp, 42,4);
INSERT INTO RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) VALUES ('Nem volt képes csak méregdrágán megjavítani a mosogatógépet', '2', current_timestamp, 43,11);
INSERT INTO RATINGS (RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) VALUES ('1', current_timestamp, 43,12);
INSERT INTO RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) VALUES ('Fiatalos lendülettel érkezett, majd rövid felmérés után megegyeztünk egymással.', '4', current_timestamp, 44,2);
INSERT INTO RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) VALUES ('Tökéletes', '5', current_timestamp, 44,8);
INSERT INTO RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) VALUES ('Igaza a mosógépem javíthatatlan volt, de legalább találtam egy biztosan jó szerelõt a továbbiakra!', '5', current_timestamp, 44,5);
INSERT INTO RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) VALUES ('Azt hittem, hogy a TV-m tönkrement, amíg nem hívtam. Pár óra múlva jobb volt mint a régi', '5', current_timestamp, 46,2);
INSERT INTO RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) VALUES ('Kisebb elõtetõt rendeltem tõlük, 2 héten belül már kész is volt', '5', current_timestamp, 47,3);
INSERT INTO RATINGS (RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) VALUES ('3', current_timestamp, 47,11);
INSERT INTO RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) VALUES ('A tetõtér beépítésére hívtuk, nagyon elfoglalt volt, de mégis szorított nekünk idõt, ajánlom', '4', current_timestamp, 47,12);
INSERT INTO RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) VALUES ('Késve érkezett párszor, de nagyon közvetlen, barátságos szakember!', '4', current_timestamp, 47,7);
INSERT INTO RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) VALUES ('A környéken a legjobb kõmûves csapat!', '5', current_timestamp, 47,9);
INSERT INTO RATINGS (RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) VALUES ('3', current_timestamp, 47,4);
INSERT INTO RATINGS (RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) VALUES ('5', current_timestamp, 48,4);
INSERT INTO RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) VALUES ('Nem ajánlom', '2', current_timestamp, 48,7);
INSERT INTO RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) VALUES ('Gyorsan készen voltak, látszik, hogy nem az idõhúzás a céljuk!', '5', current_timestamp, 49,2);
INSERT INTO RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) VALUES ('A modora hagyott kívánnivalót maga után, de a szakértelme megkérdõjelezhetetlen', '3', current_timestamp, 49,11);
INSERT INTO RATINGS (RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) VALUES ('4', current_timestamp, 51,11);
INSERT INTO RATINGS (CONTENT, RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) VALUES ('Pontos és egyben alapos is.', '5', current_timestamp, 51,12);
INSERT INTO RATINGS (RATING, TIMESTAMP, RECIPIENT_ID, SENDER_ID) VALUES ('4', current_timestamp, 51,2);

INSERT INTO WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) VALUES (13,1);
INSERT INTO WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) VALUES (14,1);
INSERT INTO WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) VALUES (15,1);
INSERT INTO WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) VALUES (16,1);
INSERT INTO WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) VALUES (17,1);
INSERT INTO WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) VALUES (18,2);
INSERT INTO WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) VALUES (18,3);
INSERT INTO WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) VALUES (18,7);
INSERT INTO WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) VALUES (18,8);
INSERT INTO WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) VALUES (19,10);
INSERT INTO WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) VALUES (20,22);
INSERT INTO WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) VALUES (21,22);
INSERT INTO WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) VALUES (22,22);
INSERT INTO WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) VALUES (23,30);
INSERT INTO WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) VALUES (25,30);
INSERT INTO WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) VALUES (24,30);
INSERT INTO WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) VALUES (25,28);
INSERT INTO WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) VALUES (26,16);
INSERT INTO WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) VALUES (27,1);
INSERT INTO WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) VALUES (27,24);
INSERT INTO WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) VALUES (28,1);
INSERT INTO WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) VALUES (29,1);
INSERT INTO WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) VALUES (29,11);
INSERT INTO WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) VALUES (30,11);
INSERT INTO WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) VALUES (30,9);
INSERT INTO WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) VALUES (31,9);
INSERT INTO WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) VALUES (32,9);
INSERT INTO WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) VALUES (32,10);
INSERT INTO WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) VALUES (33,17);
INSERT INTO WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) VALUES (33,18);
INSERT INTO WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) VALUES (34,18);
INSERT INTO WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) VALUES (35,10);
INSERT INTO WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) VALUES (36,6);
INSERT INTO WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) VALUES (36,7);
INSERT INTO WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) VALUES (37,9);
INSERT INTO WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) VALUES (38,19);
INSERT INTO WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) VALUES (38,20);
INSERT INTO WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) VALUES (39,24);
INSERT INTO WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) VALUES (40,24);
INSERT INTO WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) VALUES (40,25);
INSERT INTO WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) VALUES (40,22);
INSERT INTO WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) VALUES (41,17);
INSERT INTO WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) VALUES (42,12);
INSERT INTO WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) VALUES (42,13);
INSERT INTO WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) VALUES (43,15);
INSERT INTO WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) VALUES (44,10);
INSERT INTO WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) VALUES (44,11);
INSERT INTO WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) VALUES (45,2);
INSERT INTO WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) VALUES (45,3);
INSERT INTO WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) VALUES (45,4);
INSERT INTO WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) VALUES (45,5);
INSERT INTO WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) VALUES (45,6);
INSERT INTO WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) VALUES (46,6);
INSERT INTO WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) VALUES (46,5);
INSERT INTO WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) VALUES (47,11);
INSERT INTO WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) VALUES (48,11);
INSERT INTO WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) VALUES (49,28);
INSERT INTO WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) VALUES (49,30);
INSERT INTO WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) VALUES (50,24);
INSERT INTO WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) VALUES (50,25);
INSERT INTO WORKERS_LOCATIONS (WORKER_ID, LOCATIONS_ID) VALUES (51,1);